/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maha
 */
public class MainFram extends javax.swing.JFrame {

    /**
     * Creates new form MainFram
     */
    public MainFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addStudent = new javax.swing.JLabel();
        deleteStudent = new javax.swing.JLabel();
        committeeInfo = new javax.swing.JLabel();
        memberRegistration = new javax.swing.JLabel();
        sendRequest = new javax.swing.JLabel();
        studentInfo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));

        addStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentMouseClicked(evt);
            }
        });

        deleteStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Delet.png"))); // NOI18N
        deleteStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteStudentMouseClicked(evt);
            }
        });

        committeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/comittee-info.png"))); // NOI18N
        committeeInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        committeeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                committeeInfoMouseClicked(evt);
            }
        });

        memberRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Member.png"))); // NOI18N
        memberRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        memberRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberRegistrationMouseClicked(evt);
            }
        });

        sendRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/request.png"))); // NOI18N
        sendRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendRequestMouseClicked(evt);
            }
        });

        studentInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student-info.png"))); // NOI18N
        studentInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentInfoMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 168, 168));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addStudent)
                    .addComponent(sendRequest)
                    .addComponent(committeeInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(studentInfo)
                    .addComponent(deleteStudent)
                    .addComponent(memberRegistration))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteStudent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addStudent, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendRequest, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(memberRegistration, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentInfo)
                    .addComponent(committeeInfo))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 890));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentMouseClicked
        // TODO add your handling code here:
        //dispose(); if i want to close this
        AddStudent addStudentFrame = new AddStudent();
        addStudentFrame.setVisible(true);
        
    }//GEN-LAST:event_addStudentMouseClicked

    private void deleteStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteStudentMouseClicked
        // TODO add your handling code here:
        DeleteStudent deleteStuFrame = new DeleteStudent();
       deleteStuFrame.setVisible(true);
    }//GEN-LAST:event_deleteStudentMouseClicked

    private void committeeInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_committeeInfoMouseClicked
CommitteeInfo committeeinfo=new CommitteeInfo();
       committeeinfo.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_committeeInfoMouseClicked

    private void memberRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberRegistrationMouseClicked
        // TODO add your handling code here:
        MemberRegistration registraionFrame = new MemberRegistration();
        registraionFrame.setVisible(true);
    }//GEN-LAST:event_memberRegistrationMouseClicked

    private void sendRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendRequestMouseClicked
        // TODO add your handling code here:
        RequestEvent requestFrame = new RequestEvent();
        requestFrame.setVisible(true);
    }//GEN-LAST:event_sendRequestMouseClicked

    private void studentInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentInfoMouseClicked
 StudentInformation studentinformation = new StudentInformation();
        studentinformation.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_studentInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addStudent;
    private javax.swing.JLabel committeeInfo;
    private javax.swing.JLabel deleteStudent;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel memberRegistration;
    private javax.swing.JLabel sendRequest;
    private javax.swing.JLabel studentInfo;
    // End of variables declaration//GEN-END:variables
}
