/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raghad
 */
import java.sql.*;
import javax.swing.JOptionPane;
public class MemberRegistration extends javax.swing.JFrame {

    /**
     * Creates new form inter_face
     */
    public MemberRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        studentID = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label3 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        moreInfo = new java.awt.Button();
        committeeList = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        register = new java.awt.Button();

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(249, 249, 249));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setBackground(new java.awt.Color(249, 249, 249));
        label2.setFont(new java.awt.Font("Lato Semibold", 0, 18)); // NOI18N
        label2.setText("Student ID:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 213, 125, -1));

        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 213, 156, 34));

        jPanel1.setBackground(new java.awt.Color(0, 168, 168));

        label4.setFont(new java.awt.Font("Lato Heavy", 0, 50)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Member Registration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 170));

        label3.setBackground(new java.awt.Color(249, 249, 249));
        label3.setFont(new java.awt.Font("Lato Semibold", 0, 20)); // NOI18N
        label3.setText("Choose Committee");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 329, 223, -1));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        moreInfo.setBackground(new java.awt.Color(0, 168, 168));
        moreInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        moreInfo.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        moreInfo.setForeground(new java.awt.Color(255, 255, 255));
        moreInfo.setLabel("Click here");
        moreInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moreInfoMouseClicked(evt);
            }
        });

        committeeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islamic", "Technique", "Social", "Sports", "Multimedia" }));

        label1.setBackground(new java.awt.Color(249, 249, 249));
        label1.setFont(new java.awt.Font("Lato Medium", 1, 18)); // NOI18N
        label1.setText("More info. about committee");

        register.setBackground(new java.awt.Color(248, 120, 42));
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 255));
        register.setLabel("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(committeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moreInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(committeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moreInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        try {
            String url = "jdbc:oracle:oci8:@localhost:1521:Maha";
            String password = "hr";
            String username = "hr";
            Connection con = DriverManager.getConnection(url, username, password);
            Statement stm = con.createStatement();
            //int sal = Integer.valueOf(salarytext.getText());
            //String query = "INSERT INTO STUDENT VALUES('" + SID.getText() + "','" + SName.getText() + "','" + Sphone.getText() + "'," + Semail.getText() + "')";
            
            if (studentID.getText() == null ||committeeList.getSelectedItem()==null) {
                //-------------------------- missing info --------------------------
                JOptionPane.showMessageDialog(null, "Missing Date", "Error", JOptionPane.ERROR_MESSAGE);
                
            } else {
                
                int choice = JOptionPane.showConfirmDialog(null, "Do you realy want to register in "+committeeList.getSelectedItem()+ " committee ", "Member Registeration ", JOptionPane.YES_NO_OPTION);
                //0 is the point
                
                int selectedCommittee = committeeList.getSelectedIndex();
                int cid = -1;
                switch (selectedCommittee) {
                    case 0:
                        cid = 10;
                        break;
                    case 1:
                        cid = 11;
                        break;
                    case 2:
                        cid = 12;
                        break;
                    case 3:
                        cid = 13;
                        break;
                    case 4:
                        cid = 14;
                        break;
                }
                if (choice == 0) {
                    //-------------------------- Yes Add student --------------------------
                    String query = "insert into part_off values ('" + studentID.getText() + "' , '" + cid + "' )";
                    stm.execute(query);
                    JOptionPane.showMessageDialog(null, "Member Successfully Added");
                }
                
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_registerMouseClicked

    private void moreInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreInfoMouseClicked
        // TODO add your handling code here:
        
        CommitteeInfo committeeinfo=new CommitteeInfo();
        committeeinfo.setVisible(true);
    }//GEN-LAST:event_moreInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> committeeList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Button moreInfo;
    private java.awt.Button register;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
